version = 0.1
[default.deploy.parameters]
stack_name = "camera-app"
region = "us-east-1"
profile = "planttracer"
resolve_s3 = true
s3_prefix = "camera-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = false
parameter_overrides = "UsersTableName=\"e11-users\" OidcSecretId=\"arn:aws:secretsmanager:us-east-1:586794483136:secret:harvardkey-oidc-JGPzjb\" SshSecretId=\"arn:aws:secretsmanager:us-east-1:586794483136:secret:ssh-keys-EqRSxl\" HostedZoneId=\"Z05034072HOMXYCK23BRA\" HostedZoneId=\"Z05034072HOMXYCK23BRA\" CertificateArn=\"\" LogLevel=\"DEBUG\""
image_repositories = []
template_file = ".aws-sam/build/template.yaml"

[default.build.parameters]
cached = false
parallel=true
